name: get_links
description: to get links easily
version: 0.0.3
author: AQuadic Software Solutions (Hello@AQuadic.com)
homepage: https://github.com/TinyProgrammers/get_links_package

environment:
  sdk: ">=2.11.0 <3.0.0"
