name: get_links
description: to get links easily
version: 0.0.1
author:
homepage: https://github.com/TinyProgrammers/get_links_package

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #dio Connect.
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1

  # Webview
#  webview_flutter: ^1.0.7

dev_dependencies:
  dapackages: ^1.4.0  # flutter pub pub run dapackages:dapackages.dart ./pubspec.yaml
